apiVersion: apps/v1
kind: Deployment 
metadata:
  name: webapp
spec:
  # modify replicas according to your case
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5



---
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod-0.5
  labels:
    app: webapp
    release: "0-5"
spec:
  containers:
  - name: webapp
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queeue
spec:
  containers:
  - name: queue
    image: richardchesterwood/k8s-fleetman-queue:release1

