apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
        #this defines which pods are going to br represented by this service, this service become endpoint 
  selector:
    app: queue
    release: "0-5"
  ports:
  - name: http
    port: 8161
    #targetPort: 80
    nodePort: 30010 

  type: NodePort

